### ISSUE TITLE
SQSError: SQS receive message failed: The specified queue does not exist for this wsdl version.

### ISSUE THREAD

**Issue by AGDholo** [nestjs-packages/sqs#146]
I follow the readme,

```
@Module({
  imports: [
    SqsModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => {
        const config = {
          region: configService.get('AWS_SQS_REGION'),
          endpoint: configService.get('AWS_SQS_ENDPOINT'),
          accountNumber: configService.get('AWS_SQS_ACCOUNT_ID'),
          credentials: {
            accessKeyId: configService.get('AWS_ACCESS_KEY_ID'),
            secretAccessKey: configService.get('AWS_SECRET_ACCESS_KEY'),
          },
        };
        return new SqsConfig(config);
      },
    }),
    SqsModule.registerQueue({
      name: 'preview-queue.fifo',
      type: SqsQueueType.Consumer, // 'ALL'|'CONSUMER'|'PRODUCER'
      consumerOptions: {},
      producerOptions: {},
    }),
  ],
  providers: [AwsOpenSearchQueue],
```

### AwsOpenSearchQueue
```
import {
  SqsConsumerEvent,
  SqsConsumerEventHandler,
  SqsMessageHandler,
  SqsProcess,
} from '@nestjs-packages/sqs';

@SqsProcess(/** name: */ 'preview-queue.fifo')
export class AwsOpenSearchQueue {
  @SqsMessageHandler(/** batch: */ false)
  public async handleMessage(message: AWS.SQS.Message) {}

  @SqsConsumerEventHandler(/** eventName: */ SqsConsumerEvent.PROCESSING_ERROR)
  public onProcessingError(error: Error, message: AWS.SQS.Message) {
    // report errors here
  }
}
```

But it's not work,
Console log: 
```
node_modules\sqs-consumer\dist\consumer.js:45
    const sqsError = new errors_1.SQSError(message);
                     ^
SQSError: SQS receive message failed: The specified queue does not exist for this wsdl version.
    at toSQSError (D:\repo\backend-nestjs-graphQL-prisma\node_modules\sqs-consumer\dist\consumer.js:45:22)       
    at Consumer.receiveMessage (D:\repo\backend-nestjs-graphQL-prisma\node_modules\sqs-consumer\dist\consumer.js:157:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Actually, I don't know How can I registerQueue, Is there some example? Thanks.

**Comment by AGDholo** [comment]
Fixed it,

Change the sqs type to ALL

```
    SqsModule.registerQueue({
      name: 'preview-queue.fifo',
      type: SqsQueueType.All, // 'ALL'|'CONSUMER'|'PRODUCER'
    }),
```

And set the AWS_SQS_ENDPOINT by aws document
https://docs.aws.amazon.com/general/latest/gr/sqs-service.html
